namesrvAddr=127.0.0.1:9876
brokerClusterName=DefaultCluster
brokerName=a
listenPort=11010
brokerId=0
defaultTopicQueueNums=8
autoCreateTopicEnable=false
storePathRootDir=/data/broker-a-0/store
storePathCommitLog=/data/broker-a-0/store/commitlog
deleteWhen=01;02;03;04;05;06;07;08;09;10;11;12;13;14;15;16;17;18;19;20;21;22;23;24
fileReservedTime=1
brokerRole=SYNC_MASTER
flushDiskType=ASYNC_FLUSH
haSendHeartbeatInterval=3000
waitTimeMillsInSendQueue=6000
osPageCacheBusyTimeOutMills=5000
useReentrantLockWhenPutMessage=true
sendMessageThreadPoolNums=32
warmMapedFileEnable=false
transferMsgByHeap=false
haTransferBatchSize=163840
serverSelectorThreads=16
serverWorkerThreads=32
# for commitlog sync debug
diskMaxUsedSpaceRatio=60
mappedFileSizeCommitLog=20971520